services:
  home:
    container_name: "main_landing_page"
    build: 
      context: './home/'
      dockerfile: 'Dockerfile'
    stop_signal: SIGKILL


  nginx:
    container_name: "main_balancer"
    image: "nginx:latest"
    volumes: 
      - ../volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../volumes/nginx/snippets/:/etc/nginx/snippets/
      - ../volumes/static/:/var/www/static/
      - ../../keys/:/etc/ssl/certs/
    depends_on:
      - home
    ports:
      - 550:443
    links:
      - home