
services:
  home:
    container_name: "Homepage"
    build: 
      context: './home/'
      dockerfile: 'Dockerfile'
    stop_signal: SIGKILL

  nginx:
    container_name: "Nginx"
    image: "nginx:latest"
    volumes: 
      - ../volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../volumes/nginx/snippets/:/etc/nginx/snippets/
      - ../volumes/static/:/var/www/static/
    ports:
      - 8000:80
    expose:
      - 8000
    depends_on:
      - home