
services:
  home:
    container_name: "Homepage"
    build: 
      context: './home/'
      dockerfile: 'Dockerfile'
    stop_signal: SIGKILL

  nginx:
    container_name: "Nginx"
    image: "nginx:latest"
    volumes: 
      - ../volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../volumes/nginx/snippets/:/etc/nginx/snippets/
      - ../volumes/static/:/var/www/static/
    ports:
      - 8000:80
    expose:
      - 8000
    depends_on:
      - home
      - minecraft
  minecraft:
    container_name: 'Spigot_1.19.3'
    image: openjdk:latest
    command: bash -c "cd /minecraft/ && java -jar paper.jar"
    volumes:
      - ../volumes/jaocraft/:/minecraft/
    ports:
      - 8123:8123
      - 25565:25565
      - 8125:25564
    expose:
      - 8123:8123
      - 25565:25565
      - 8125:25564
