services:
  home:
    container_name: "Homepage"
    build: 
      context: './home/'
      dockerfile: 'Dockerfile'
    stop_signal: SIGKILL
    networks:
      default:
        ipv4_address: 10.1.0.3
  nginx:
    container_name: "Nginx"
    image: "nginx:latest"
    volumes: 
      - ../volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../volumes/nginx/snippets/:/etc/nginx/snippets/
      - ../volumes/static/:/var/www/static/
    depends_on:
      - home
      - minecraft
    networks:
      default:
        ipv4_address: 10.1.0.4
  minecraft:
    container_name: 'Spigot_1.19.3'
    image: openjdk:latest
    command: bash -c "cd /minecraft/ && java -jar paper.jar"
    volumes:
      - ../volumes/jaocraft/:/minecraft/
    expose:
      - 8123:8123
      - 25565:25565
      - 8125:25564
    networks:
      default:
        ipv4_address: 10.1.0.5
  
networks:
  default:
    external:
      name: external-network
